[package]
name = "shallenge"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.9"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = false
debug = false
incremental = false
overflow-checks = false
